// qgemm_driver.cpp
//
// Driver-API binding for the sm_61 DP4A kernel. Same qgemm_forward() Python
// signature as qgemm_binding.cpp, but launches NVRTC-built PTX
// (qgemm_ptx.h, generated by ptx_build.py) via cuLaunchKernel instead of
// the <<<>>> syntax — so this file is plain C++ that cl compiles with NO
// nvcc in the loop. (nvcc 12.9's cudafe++ access-violates with VS18 MSVC
// 14.51 headers on this box; NVRTC never parses MSVC headers.)

#include <torch/extension.h>
#include <ATen/cuda/CUDAContext.h>
#include <cuda.h>

#include <mutex>
#include <stdexcept>

#include "qgemm_ptx.h"

#define CUCHK(expr) do { \
    CUresult _r = (expr); \
    if (_r != CUDA_SUCCESS) { \
        const char* _s = "unknown"; \
        cuGetErrorString(_r, &_s); \
        throw std::runtime_error(std::string("CUDA driver error: ") + _s); \
    } \
} while (0)

namespace {

CUmodule g_mod = nullptr;
CUfunction g_fn = nullptr;
std::once_flag g_init;

void init_ptx() {
    CUCHK(cuModuleLoadDataEx(&g_mod, QGEMM_PTX, 0, nullptr, nullptr));
    CUCHK(cuModuleGetFunction(&g_fn, g_mod, "qgemm_i8_dp4a_kernel"));
}

}  // namespace

torch::Tensor qgemm_forward(
    torch::Tensor x_int8,   // [M, K] int8, contiguous, CUDA
    torch::Tensor w_int8,   // [N, K] int8, contiguous, CUDA (pre-transposed weight)
    torch::Tensor x_scale,  // [M]    float32, CUDA
    torch::Tensor w_scale)  // [N]    float32, CUDA
{
    TORCH_CHECK(x_int8.is_cuda() && w_int8.is_cuda(), "x and w must be CUDA tensors");
    TORCH_CHECK(x_scale.is_cuda() && w_scale.is_cuda(), "scales must be CUDA tensors");
    TORCH_CHECK(x_int8.scalar_type() == torch::kInt8, "x must be int8");
    TORCH_CHECK(w_int8.scalar_type() == torch::kInt8, "w must be int8");
    TORCH_CHECK(x_scale.scalar_type() == torch::kFloat32, "x_scale must be float32");
    TORCH_CHECK(w_scale.scalar_type() == torch::kFloat32, "w_scale must be float32");
    TORCH_CHECK(x_int8.is_contiguous() && w_int8.is_contiguous(), "x and w must be contiguous");
    TORCH_CHECK(x_int8.dim() == 2 && w_int8.dim() == 2, "x and w must be 2D");

    const int64_t M = x_int8.size(0);
    const int64_t K = x_int8.size(1);
    const int64_t N = w_int8.size(0);
    TORCH_CHECK(w_int8.size(1) == K, "K mismatch");
    TORCH_CHECK(x_scale.numel() == M, "x_scale must have M elements");
    TORCH_CHECK(w_scale.numel() == N, "w_scale must have N elements");

    std::call_once(g_init, init_ptx);

    auto y = torch::empty({M, N}, x_int8.options().dtype(torch::kFloat16));

    // Mirror the nvcc launcher: block(TILE_N=32, TILE_M=32).
    const int Mi = static_cast<int>(M);
    const int Ni = static_cast<int>(N);
    const int Ki = static_cast<int>(K);
    const unsigned gridX = static_cast<unsigned>((N + 31) / 32);
    const unsigned gridY = static_cast<unsigned>((M + 31) / 32);

    CUdeviceptr xptr = reinterpret_cast<CUdeviceptr>(x_int8.data_ptr<int8_t>());
    CUdeviceptr wptr = reinterpret_cast<CUdeviceptr>(w_int8.data_ptr<int8_t>());
    CUdeviceptr xsptr = reinterpret_cast<CUdeviceptr>(x_scale.data_ptr<float>());
    CUdeviceptr wsptr = reinterpret_cast<CUdeviceptr>(w_scale.data_ptr<float>());
    CUdeviceptr yptr = reinterpret_cast<CUdeviceptr>(y.data_ptr<at::Half>());
    void* args[] = { &xptr, &wptr, &xsptr, &wsptr, &yptr,
                     const_cast<void*>(reinterpret_cast<const void*>(&Mi)),
                     const_cast<void*>(reinterpret_cast<const void*>(&Ni)),
                     const_cast<void*>(reinterpret_cast<const void*>(&Ki)) };

    CUstream stream =
        reinterpret_cast<CUstream>(at::cuda::getCurrentCUDAStream().stream());
    CUCHK(cuLaunchKernel(g_fn, gridX, gridY, 1, 32, 32, 1,
                         0, stream, args, nullptr));
    return y;
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("qgemm_forward", &qgemm_forward,
          "Quillan sm_61 DP4A quantized INT8 GEMM -> fp16 (driver-API launch of NVRTC PTX)");
}
